export const LINK_LIST_REQUEST = 'LINK_LIST_REQUEST'
export const LINK_LIST_SUCCESS = 'LINK_LIST_SUCCESS'
export const LINK_LIST_FAIL = 'LINK_LIST_FAIL'
export const LINK_LIST_RESET = 'LINK_LIST_RESET'